// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: room.proto

//protobuf的命名空间

package room

import (
	proto "github.com/golang/protobuf/proto"
	user "github.com/my_game/module/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of user/user.proto.

type User = user.User
type Player = user.Player
type Robot = user.Robot

//房间实体
type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         //房间id
	Status uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` //状态,0:空闲中，1:满人,2:房间被锁住
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

//刷新房间的人员数
type RefreshRoomPlayersEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room       *Room          `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`             //房间
	PlayerList []*user.Player `protobuf:"bytes,2,rep,name=playerList,proto3" json:"playerList,omitempty"` //正在房间的人
	Player     *user.Player   `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`         //申请人
}

func (x *RefreshRoomPlayersEvent) Reset() {
	*x = RefreshRoomPlayersEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRoomPlayersEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRoomPlayersEvent) ProtoMessage() {}

func (x *RefreshRoomPlayersEvent) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRoomPlayersEvent.ProtoReflect.Descriptor instead.
func (*RefreshRoomPlayersEvent) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshRoomPlayersEvent) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RefreshRoomPlayersEvent) GetPlayerList() []*user.Player {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *RefreshRoomPlayersEvent) GetPlayer() *user.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

//用户加入房间的事件
type JoinEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room   *Room        `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`     //加入的房间
	Player *user.Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"` //新加入房间的用户
}

func (x *JoinEvent) Reset() {
	*x = JoinEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEvent) ProtoMessage() {}

func (x *JoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEvent.ProtoReflect.Descriptor instead.
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinEvent) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinEvent) GetPlayer() *user.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

//离开房间的消息
type LeaveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *user.Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"` //离开房间的用户
}

func (x *LeaveEvent) Reset() {
	*x = LeaveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEvent) ProtoMessage() {}

func (x *LeaveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEvent.ProtoReflect.Descriptor instead.
func (*LeaveEvent) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveEvent) GetPlayer() *user.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

//房间的流请求
type RoomStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*RoomStreamRequest_RoomPlayersEvent
	//	*RoomStreamRequest_JoinEvent
	//	*RoomStreamRequest_LeaveEvent
	Event isRoomStreamRequest_Event `protobuf_oneof:"Event"`
}

func (x *RoomStreamRequest) Reset() {
	*x = RoomStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStreamRequest) ProtoMessage() {}

func (x *RoomStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStreamRequest.ProtoReflect.Descriptor instead.
func (*RoomStreamRequest) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{4}
}

func (m *RoomStreamRequest) GetEvent() isRoomStreamRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *RoomStreamRequest) GetRoomPlayersEvent() *RefreshRoomPlayersEvent {
	if x, ok := x.GetEvent().(*RoomStreamRequest_RoomPlayersEvent); ok {
		return x.RoomPlayersEvent
	}
	return nil
}

func (x *RoomStreamRequest) GetJoinEvent() *JoinEvent {
	if x, ok := x.GetEvent().(*RoomStreamRequest_JoinEvent); ok {
		return x.JoinEvent
	}
	return nil
}

func (x *RoomStreamRequest) GetLeaveEvent() *LeaveEvent {
	if x, ok := x.GetEvent().(*RoomStreamRequest_LeaveEvent); ok {
		return x.LeaveEvent
	}
	return nil
}

type isRoomStreamRequest_Event interface {
	isRoomStreamRequest_Event()
}

type RoomStreamRequest_RoomPlayersEvent struct {
	//事件
	RoomPlayersEvent *RefreshRoomPlayersEvent `protobuf:"bytes,1,opt,name=roomPlayersEvent,proto3,oneof"`
}

type RoomStreamRequest_JoinEvent struct {
	JoinEvent *JoinEvent `protobuf:"bytes,2,opt,name=joinEvent,proto3,oneof"`
}

type RoomStreamRequest_LeaveEvent struct {
	LeaveEvent *LeaveEvent `protobuf:"bytes,3,opt,name=leaveEvent,proto3,oneof"`
}

func (*RoomStreamRequest_RoomPlayersEvent) isRoomStreamRequest_Event() {}

func (*RoomStreamRequest_JoinEvent) isRoomStreamRequest_Event() {}

func (*RoomStreamRequest_LeaveEvent) isRoomStreamRequest_Event() {}

//房间的流响应
type RoomStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*RoomStreamResponse_RoomPlayersEvent
	//	*RoomStreamResponse_JoinEvent
	//	*RoomStreamResponse_LeaveEvent
	Event isRoomStreamResponse_Event `protobuf_oneof:"Event"`
}

func (x *RoomStreamResponse) Reset() {
	*x = RoomStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStreamResponse) ProtoMessage() {}

func (x *RoomStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStreamResponse.ProtoReflect.Descriptor instead.
func (*RoomStreamResponse) Descriptor() ([]byte, []int) {
	return file_room_proto_rawDescGZIP(), []int{5}
}

func (m *RoomStreamResponse) GetEvent() isRoomStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *RoomStreamResponse) GetRoomPlayersEvent() *RefreshRoomPlayersEvent {
	if x, ok := x.GetEvent().(*RoomStreamResponse_RoomPlayersEvent); ok {
		return x.RoomPlayersEvent
	}
	return nil
}

func (x *RoomStreamResponse) GetJoinEvent() *JoinEvent {
	if x, ok := x.GetEvent().(*RoomStreamResponse_JoinEvent); ok {
		return x.JoinEvent
	}
	return nil
}

func (x *RoomStreamResponse) GetLeaveEvent() *LeaveEvent {
	if x, ok := x.GetEvent().(*RoomStreamResponse_LeaveEvent); ok {
		return x.LeaveEvent
	}
	return nil
}

type isRoomStreamResponse_Event interface {
	isRoomStreamResponse_Event()
}

type RoomStreamResponse_RoomPlayersEvent struct {
	//事件
	RoomPlayersEvent *RefreshRoomPlayersEvent `protobuf:"bytes,1,opt,name=roomPlayersEvent,proto3,oneof"`
}

type RoomStreamResponse_JoinEvent struct {
	JoinEvent *JoinEvent `protobuf:"bytes,2,opt,name=joinEvent,proto3,oneof"`
}

type RoomStreamResponse_LeaveEvent struct {
	LeaveEvent *LeaveEvent `protobuf:"bytes,3,opt,name=leaveEvent,proto3,oneof"`
}

func (*RoomStreamResponse_RoomPlayersEvent) isRoomStreamResponse_Event() {}

func (*RoomStreamResponse_JoinEvent) isRoomStreamResponse_Event() {}

func (*RoomStreamResponse_LeaveEvent) isRoomStreamResponse_Event() {}

var File_room_proto protoreflect.FileDescriptor

var file_room_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x79,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x1a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d,
	0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d,
	0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x3b, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x79, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x6f, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x04,
	0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x79, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x33, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x79,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x41, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0xfb, 0x01, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5a, 0x0a, 0x10, 0x72, 0x6f, 0x6f,
	0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x79, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x65,
	0x61, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0xfc, 0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x6d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x32, 0x67, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x12, 0x5b, 0x0a, 0x04,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x26, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d,
	0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x50, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_proto_rawDescOnce sync.Once
	file_room_proto_rawDescData = file_room_proto_rawDesc
)

func file_room_proto_rawDescGZIP() []byte {
	file_room_proto_rawDescOnce.Do(func() {
		file_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_proto_rawDescData)
	})
	return file_room_proto_rawDescData
}

var file_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_room_proto_goTypes = []interface{}{
	(*Room)(nil),                    // 0: my_game.protoc.room.Room
	(*RefreshRoomPlayersEvent)(nil), // 1: my_game.protoc.room.RefreshRoomPlayersEvent
	(*JoinEvent)(nil),               // 2: my_game.protoc.room.JoinEvent
	(*LeaveEvent)(nil),              // 3: my_game.protoc.room.LeaveEvent
	(*RoomStreamRequest)(nil),       // 4: my_game.protoc.room.RoomStreamRequest
	(*RoomStreamResponse)(nil),      // 5: my_game.protoc.room.RoomStreamResponse
	(*user.Player)(nil),             // 6: my_game.protoc.user.Player
}
var file_room_proto_depIdxs = []int32{
	0,  // 0: my_game.protoc.room.RefreshRoomPlayersEvent.room:type_name -> my_game.protoc.room.Room
	6,  // 1: my_game.protoc.room.RefreshRoomPlayersEvent.playerList:type_name -> my_game.protoc.user.Player
	6,  // 2: my_game.protoc.room.RefreshRoomPlayersEvent.player:type_name -> my_game.protoc.user.Player
	0,  // 3: my_game.protoc.room.JoinEvent.room:type_name -> my_game.protoc.room.Room
	6,  // 4: my_game.protoc.room.JoinEvent.player:type_name -> my_game.protoc.user.Player
	6,  // 5: my_game.protoc.room.LeaveEvent.player:type_name -> my_game.protoc.user.Player
	1,  // 6: my_game.protoc.room.RoomStreamRequest.roomPlayersEvent:type_name -> my_game.protoc.room.RefreshRoomPlayersEvent
	2,  // 7: my_game.protoc.room.RoomStreamRequest.joinEvent:type_name -> my_game.protoc.room.JoinEvent
	3,  // 8: my_game.protoc.room.RoomStreamRequest.leaveEvent:type_name -> my_game.protoc.room.LeaveEvent
	1,  // 9: my_game.protoc.room.RoomStreamResponse.roomPlayersEvent:type_name -> my_game.protoc.room.RefreshRoomPlayersEvent
	2,  // 10: my_game.protoc.room.RoomStreamResponse.joinEvent:type_name -> my_game.protoc.room.JoinEvent
	3,  // 11: my_game.protoc.room.RoomStreamResponse.leaveEvent:type_name -> my_game.protoc.room.LeaveEvent
	4,  // 12: my_game.protoc.room.RoomGrpc.Room:input_type -> my_game.protoc.room.RoomStreamRequest
	5,  // 13: my_game.protoc.room.RoomGrpc.Room:output_type -> my_game.protoc.room.RoomStreamResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_room_proto_init() }
func file_room_proto_init() {
	if File_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRoomPlayersEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_room_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RoomStreamRequest_RoomPlayersEvent)(nil),
		(*RoomStreamRequest_JoinEvent)(nil),
		(*RoomStreamRequest_LeaveEvent)(nil),
	}
	file_room_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*RoomStreamResponse_RoomPlayersEvent)(nil),
		(*RoomStreamResponse_JoinEvent)(nil),
		(*RoomStreamResponse_LeaveEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_proto_goTypes,
		DependencyIndexes: file_room_proto_depIdxs,
		MessageInfos:      file_room_proto_msgTypes,
	}.Build()
	File_room_proto = out.File
	file_room_proto_rawDesc = nil
	file_room_proto_goTypes = nil
	file_room_proto_depIdxs = nil
}
